#!/bin/sh

export JAVA_HOME="/shared/common/ibm-java2-ppc-50/"
export ANT_HOME="$HOME/src/eclipse/plugins/org.apache.ant_1.6.5/"

if [ -z "$1" ]; then 
    echo usage: $0 "<Message title> <Message Description> <Message Contributor>"
    exit
fi
if [ -z "$2" ]; then 
    echo usage: $0 "<Message title> <Message Description> <Message Contributor>"
    exit
fi
if [ -z "$3" ]; then 
    echo usage: $0 "<Message title> <Message Description> <Message Contributor>"
    exit
fi

ant --noconfig -lib ext-lib -f rss.xml addMessage -DrssTitle="$1" -DrssMessageDescription="$2" -DrssMessageContributor="$3"
ant --noconfig -lib ext-lib -f rss.xml generateRss 
ant --noconfig -lib ext-lib -f rss.xml uploadRss
