#!/bin/sh

export JAVA_HOME="/shared/common/ibm-java2-ppc-50/"
export ANT_HOME="$HOME/src/eclipse/plugins/org.apache.ant_1.6.5/"

if [ -z "$1" ]; then 
    echo usage: $0 "<Message title> <Message Description> <Message Contributor>"
    exit
fi

#create the bug status
rm summary
rm result.html 
rm bugs 
php5 fetch_bugs.php

# short summary
ant --noconfig -lib ext-lib -f rss.xml getTestResults

# mail results
ant --noconfig -lib ext-lib -f rss.xml mailUnitTestResults

# add message
ant --noconfig -lib ext-lib -f rss.xml addMessage -DrssTitle="$1" 

# add bugs message
ant --noconfig -lib ext-lib -f rss.xml addBugsMessage 

# generate the RSS
ant --noconfig -lib ext-lib -f rss.xml generateRss 

# replace the &amp char to enable html tags
php5 replaceAmp.php

# uploads the RSS
ant --noconfig -lib ext-lib -f rss.xml uploadRss

# uploads the Report
ant --noconfig -lib ext-lib -f rss.xml uploadReport
