<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>twig</string>
	</array>
	<key>foldingStartMarker</key>
	<string>{% (block|if|else|elseif|for)</string>
	<key>foldingStopMarker</key>
	<string>{% (endblock|endif|endfor|trigger|url) %}</string>
	<key>keyEquivalent</key>
	<string>^~T</string>
	<key>name</key>
	<string>HTML (Twig)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Since html is valid in Twig templates include the html patterns</string>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>{#</string>
			<key>end</key>
			<string>#}</string>
			<key>name</key>
			<string>comment.block.twig</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\$[a-z_\.]+</string>
			<key>name</key>
			<string>variable.other.twig</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\${</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.twig</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>variable.other.twig</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\|(\s?)([^\( ]+)\b</string>
					<key>name</key>
					<string>support.function.filter.twig</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.twig</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.twig</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.twig</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.twig</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.twig</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.twig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[a-zA-Z_]+</string>
					<key>name</key>
					<string>string.unquoted.twig</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>{%</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.twig</string>
				</dict>
			</dict>
			<key>end</key>
			<string>%}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.twig</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.template.twig</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(block|endblock|extends|for|endfor|if|include|else|elseif|endif|trigger|url)\b</string>
					<key>name</key>
					<string>keyword.control.twig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(and|or|not|in|by|as)\b</string>
					<key>name</key>
					<string>keyword.operator.twig</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.twig</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.twig</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.twig</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.twig</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.twig</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.twig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[a-zA-Z_]+</string>
					<key>name</key>
					<string>string.unquoted.twig</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.twig</string>
	<key>uuid</key>
	<string>4E0E1804-0A52-4E0B-BD99-37AFAF9823D3</string>
</dict>
</plist>
