/*******************************************************************************
 * Copyright (c) 2006 Zend Corporation and IBM Corporation.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   Zend and IBM - Initial implementation
 *******************************************************************************/

//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Sun Oct 15 16:12:12 IST 2006
//----------------------------------------------------

package org.eclipse.php.core.phpModel.parser.php5;

/** CUP generated interface containing symbol constants. */
public interface ParserConstants5 {
  /* terminals */
  public static final int T_BOOLEAN_AND = 93;
  public static final int T_INLINE_HTML = 10;
  public static final int T_EMPTY = 45;
  public static final int T_PROTECTED = 135;
  public static final int T_CLOSE_RECT = 126;
  public static final int T_IS_NOT_EQUAL = 98;
  public static final int T_INCLUDE = 68;
  public static final int T_QUATE = 141;
  public static final int T_GLOBAL = 41;
  public static final int T_PRINT = 77;
  public static final int T_OR_EQUAL = 86;
  public static final int T_LOGICAL_XOR = 75;
  public static final int T_FUNCTION = 34;
  public static final int T_STATIC = 131;
  public static final int T_NEKUDA = 114;
  public static final int T_THROW = 39;
  public static final int T_CLASS = 47;
  public static final int T_ABSTRACT = 132;
  public static final int T_ENCAPSED_AND_WHITESPACE = 13;
  public static final int T_MOD_EQUAL = 84;
  public static final int T_BREAK = 32;
  public static final int T_WHILE = 17;
  public static final int T_DO = 16;
  public static final int T_CONST = 35;
  public static final int T_CONTINUE = 33;
  public static final int T_FUNC_C = 57;
  public static final int T_DIV = 110;
  public static final int T_LOGICAL_OR = 74;
  public static final int T_OPEN_PARENTHESE = 137;
  public static final int T_REFERENCE = 96;
  public static final int T_COMMA = 73;
  public static final int T_ELSE = 130;
  public static final int T_IS_EQUAL = 97;
  public static final int T_LIST = 53;
  public static final int T_OR = 94;
  public static final int T_IS_IDENTICAL = 99;
  public static final int T_INC = 115;
  public static final int T_ELSEIF = 129;
  public static final int T_TRY = 37;
  public static final int T_PRIVATE = 134;
  public static final int T_UNSET_CAST = 123;
  public static final int T_INCLUDE_ONCE = 69;
  public static final int T_ENDIF = 128;
  public static final int T_SR_EQUAL = 89;
  public static final int EOF = 0;
  public static final int T_PUBLIC = 136;
  public static final int T_OBJECT_OPERATOR = 51;
  public static final int T_TILDA = 113;
  public static final int T_PAAMAYIM_NEKUDOTAYIM = 65;
  public static final int T_IS_SMALLER_OR_EQUAL = 101;
  public static final int T_XOR_EQUAL = 87;
  public static final int T_ENDFOREACH = 22;
  public static final int T_CONSTANT_ENCAPSED_STRING = 14;
  public static final int T_BACKQUATE = 142;
  public static final int T_AT = 124;
  public static final int T_AS = 27;
  public static final int T_CURLY_CLOSE = 64;
  public static final int T_ENDDECLARE = 24;
  public static final int T_CATCH = 38;
  public static final int T_CASE = 30;
  public static final int T_VARIABLE = 8;
  public static final int T_NEW = 127;
  public static final int T_MINUS_EQUAL = 80;
  public static final int T_PLUS = 107;
  public static final int T_SL_EQUAL = 88;
  public static final int T_ENDWHILE = 18;
  public static final int T_ENDFOR = 20;
  public static final int T_CLONE = 26;
  public static final int T_BOOLEAN_OR = 92;
  public static final int T_UNSET = 43;
  public static final int T_INTERFACE = 48;
  public static final int T_SWITCH = 28;
  public static final int T_IS_GREATER_OR_EQUAL = 102;
  public static final int T_OPEN_RECT = 125;
  public static final int T_FINAL = 133;
  public static final int T_REQUIRE = 71;
  public static final int T_FILE = 59;
  public static final int T_BAD_CHARACTER = 12;
  public static final int T_DEC = 116;
  public static final int T_CLOSE_PARENTHESE = 138;
  public static final int T_CLASS_C = 55;
  public static final int T_EVAL = 70;
  public static final int T_RGREATER = 103;
  public static final int T_IS_NOT_IDENTICAL = 100;
  public static final int T_NOT = 112;
  public static final int T_REQUIRE_ONCE = 72;
  public static final int T_DOLLAR_OPEN_CURLY_BRACES = 62;
  public static final int T_VAR = 42;
  public static final int T_START_HEREDOC = 60;
  public static final int T_ENDSWITCH = 29;
  public static final int T_OBJECT_CAST = 121;
  public static final int T_ECHO = 15;
  public static final int T_LINE = 58;
  public static final int T_FOR = 19;
  public static final int T_IMPLEMENTS = 50;
  public static final int T_ARRAY_CAST = 120;
  public static final int T_CHARACTER = 11;
  public static final int T_TIMES = 109;
  public static final int T_DOLLAR = 140;
  public static final int T_DOUBLE_CAST = 118;
  public static final int T_BOOL_CAST = 122;
  public static final int T_PRECENT = 111;
  public static final int T_LNUMBER = 4;
  public static final int T_CURLY_OPEN = 63;
  public static final int T_DEFINE = 67;
  public static final int T_QUESTION_MARK = 90;
  public static final int T_USE = 40;
  public static final int T_KOVA = 95;
  public static final int T_IF = 3;
  public static final int T_MUL_EQUAL = 81;
  public static final int T_ARRAY = 54;
  public static final int T_LGREATER = 104;
  public static final int T_SEMICOLON = 91;
  public static final int T_NEKUDOTAIM = 139;
  public static final int T_VAR_COMMENT = 66;
  public static final int T_CONCAT_EQUAL = 83;
  public static final int T_SINGLE_QUATE = 143;
  public static final int T_AND_EQUAL = 85;
  public static final int T_DNUMBER = 5;
  public static final int T_MINUS = 108;
  public static final int T_FOREACH = 21;
  public static final int T_EXIT = 2;
  public static final int T_DECLARE = 23;
  public static final int T_STRING_VARNAME = 7;
  public static final int T_EXTENDS = 49;
  public static final int T_METHOD_C = 56;
  public static final int T_INT_CAST = 117;
  public static final int T_ISSET = 44;
  public static final int T_LOGICAL_AND = 76;
  public static final int error = 1;
  public static final int T_RETURN = 36;
  public static final int T_DEFAULT = 31;
  public static final int T_SR = 106;
  public static final int T_EQUAL = 78;
  public static final int T_SL = 105;
  public static final int T_END_HEREDOC = 61;
  public static final int T_DOUBLE_ARROW = 52;
  public static final int T_STRING_CAST = 119;
  public static final int T_STRING = 6;
  public static final int T_PLUS_EQUAL = 79;
  public static final int T_INSTANCEOF = 25;
  public static final int T_DIV_EQUAL = 82;
  public static final int T_NUM_STRING = 9;
  public static final int T_HALT_COMPILER = 46;
}

