<?php

// autoload_namespaces.php generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'test' => $baseDir . '/src',
    'gossi\\ldap' => $vendorDir . '/gossi/ldap/src',
    'Symfony\\Component\\Console\\' => $vendorDir . '/symfony/console/',
);
